name: ur_health
description: "UR Health â€“ Smart Health Monitoring App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  lottie: ^3.1.0
  flutter_reactive_ble: ^5.0.3
  provider: ^6.1.2
  cloud_firestore: ^4.15.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  connectivity_plus: ^5.0.2
  permission_handler: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # -------------------- ASSETS --------------------
  assets:
      - assets/icons/navigation/
      - assets/lottie/

  # -------------------- FONTS ---------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# -------------------- APP ICON --------------------
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/app_icon_foreground.png
